[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sigil = "FQcz9eg5m16g62TRGoE987ZEmWuWx591WjqJEHtaB5pf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
